version: '3.4'

services:
  alpine-beef-xss:
    image: ibuetler/beef
    hostname: 'beef'
    environment:
      - "domainname=idocker.vuln.land"
      - "BEEF_USERNAME=hacker"
      - "BEEF_PASSWORD=compass"
      - "BEEF_FQDN=beef.idocker.vuln.land"
    ports:
      - 443:443


