version: '3.4'

services:
  alpine-beef-xss-hobo:
    image: hackinglab/alpine-beef-xss
    hostname: 'hobo'
    environment:
      - "domainname=idocker.REALM_DOMAIN_SUFFIX"
      - "BEEF_USERNAME=hacker"
      - "BEEF_PASSWORD=compass"
      - "BEEF_FQDN=localhost"
    ports:
      - "3000:3000"
